// Decompiled with JetBrains decompiler
// Type: MessageEvent_OnRaceGrid
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C496ACE-0409-4428-BF50-DF04E26AD4C0
// Assembly location: D:\Steam\steamapps\common\Motorsport Manager\MM_Data\Managed\Assembly-CSharp.dll

public class MessageEvent_OnRaceGrid : MessageEvent
{
  public void DoEvent(MessageData data)
  {
    Driver[] driverArray = new Driver[Team.mainDriverCount];
    driverArray[0] = data.GetMap("Driver1") as Driver;
    driverArray[1] = data.GetMap("Driver2") as Driver;
    Player player = Game.instance.player;
    for (int index = 0; index < Team.mainDriverCount; ++index)
    {
      Driver driver = driverArray[index];
      Message message1 = MessageManager.CreateMessage();
      message1.SetSender((Person) driver);
      message1.SetReceiver((Person) player);
      DriverMentalState.Emotion emotion = driver.mentalState.emotion;
      switch (emotion)
      {
        case DriverMentalState.Emotion.Angry:
          message1.description = Localisation.GetTextFromGroup("AngryAboutQualifyingIntro");
          Message message2 = MessageManager.CreateMessage();
          message2.description = Localisation.GetTextFromGroup("AngryAboutQualifyingOption1");
          message2.AddConversationResponseDelay();
          message2.SetSender((Person) player);
          message2.SetReceiver((Person) driver);
          message1.AddResponse(message2);
          Message message3 = MessageManager.CreateMessage();
          message3.description = Localisation.GetTextFromGroup("AngryAboutQualifyingOption1Response");
          message3.autoRespond = true;
          message3.AddConversationResponseDelay();
          message3.SetSender((Person) driver);
          message3.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState1 = new MessageAction_SetDriverMentalState();
          driverMentalState1.SetEmotion(DriverMentalState.Emotion.FiredUp);
          message3.messageAction = (MessageAction) driverMentalState1;
          message2.AddResponse(message3);
          Message message4 = MessageManager.CreateMessage();
          message4.description = Localisation.GetTextFromGroup("AngryAboutQualifyingOption2");
          message4.AddConversationResponseDelay();
          message4.SetSender((Person) player);
          message4.SetReceiver((Person) driver);
          message1.AddResponse(message4);
          Message message5 = MessageManager.CreateMessage();
          message5.description = Localisation.GetTextFromGroup("AngryAboutQualifyingOption2Response");
          message5.autoRespond = true;
          message5.AddConversationResponseDelay();
          message5.SetSender((Person) driver);
          message5.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState2 = new MessageAction_SetDriverMentalState();
          driverMentalState2.SetEmotion(DriverMentalState.Emotion.VeryAngry);
          message5.messageAction = (MessageAction) driverMentalState2;
          message4.AddResponse(message5);
          Message message6 = MessageManager.CreateMessage();
          message6.description = Localisation.GetTextFromGroup("AngryAboutQualifyingOption3");
          message6.AddConversationResponseDelay();
          message6.SetSender((Person) player);
          message6.SetReceiver((Person) driver);
          message1.AddResponse(message6);
          Message message7 = MessageManager.CreateMessage();
          message7.description = Localisation.GetTextFromGroup("AngryAboutQualifyingOption3Response");
          message7.autoRespond = true;
          message7.AddConversationResponseDelay();
          message7.SetSender((Person) driver);
          message7.SetReceiver((Person) player);
          message6.AddResponse(message7);
          break;
        case DriverMentalState.Emotion.Nervous:
          message1.description = Localisation.GetTextFromGroup("NervousAboutDriverIntro");
          Message message8 = MessageManager.CreateMessage();
          message8.description = Localisation.GetTextFromGroup("NervousAboutDriverOption1");
          message8.AddConversationResponseDelay();
          message8.SetSender((Person) player);
          message8.SetReceiver((Person) driver);
          message1.AddResponse(message8);
          Message message9 = MessageManager.CreateMessage();
          message9.description = Localisation.GetTextFromGroup("NervousAboutDriverOption1Response");
          message9.autoRespond = true;
          message9.AddConversationResponseDelay();
          message9.SetSender((Person) driver);
          message9.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState3 = new MessageAction_SetDriverMentalState();
          driverMentalState3.SetEmotion(DriverMentalState.Emotion.VeryNervous);
          message9.messageAction = (MessageAction) driverMentalState3;
          message8.AddResponse(message9);
          Message message10 = MessageManager.CreateMessage();
          message10.description = Localisation.GetTextFromGroup("NervousAboutDriverOption2");
          message10.AddConversationResponseDelay();
          message10.SetSender((Person) player);
          message10.SetReceiver((Person) driver);
          message1.AddResponse(message10);
          Message message11 = MessageManager.CreateMessage();
          message11.description = Localisation.GetTextFromGroup("NervousAboutDriverOption2Response");
          message11.autoRespond = true;
          message11.AddConversationResponseDelay();
          message11.SetSender((Person) driver);
          message11.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState4 = new MessageAction_SetDriverMentalState();
          driverMentalState4.SetEmotion(DriverMentalState.Emotion.Confident);
          message11.messageAction = (MessageAction) driverMentalState4;
          message10.AddResponse(message11);
          Message message12 = MessageManager.CreateMessage();
          message12.description = Localisation.GetTextFromGroup("NervousAboutDriverOption3");
          message12.AddConversationResponseDelay();
          message12.SetSender((Person) player);
          message12.SetReceiver((Person) driver);
          message1.AddResponse(message12);
          Message message13 = MessageManager.CreateMessage();
          message13.description = Localisation.GetTextFromGroup("NervousAboutDriverOption3Response");
          message13.autoRespond = true;
          message13.AddConversationResponseDelay();
          message13.SetSender((Person) driver);
          message13.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState5 = new MessageAction_SetDriverMentalState();
          driverMentalState5.SetEmotion(DriverMentalState.Emotion.Confused);
          message13.messageAction = (MessageAction) driverMentalState5;
          message12.AddResponse(message13);
          break;
        case DriverMentalState.Emotion.Pessimistic:
          message1.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionIntro");
          Message message14 = MessageManager.CreateMessage();
          message14.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionOption1");
          message14.AddConversationResponseDelay();
          message14.SetSender((Person) player);
          message14.SetReceiver((Person) driver);
          message1.AddResponse(message14);
          Message message15 = MessageManager.CreateMessage();
          message15.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionOption1Response");
          message15.autoRespond = true;
          message15.AddConversationResponseDelay();
          message15.SetSender((Person) driver);
          message15.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState6 = new MessageAction_SetDriverMentalState();
          driverMentalState6.SetEmotion(DriverMentalState.Emotion.FiredUp);
          message15.messageAction = (MessageAction) driverMentalState6;
          message14.AddResponse(message15);
          Message message16 = MessageManager.CreateMessage();
          message16.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionOption2");
          message16.AddConversationResponseDelay();
          message16.SetSender((Person) player);
          message16.SetReceiver((Person) driver);
          message1.AddResponse(message16);
          Message message17 = MessageManager.CreateMessage();
          message17.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionOption2Response");
          message17.autoRespond = true;
          message17.AddConversationResponseDelay();
          message17.SetSender((Person) driver);
          message17.SetReceiver((Person) player);
          MessageAction_SetDriverMentalState driverMentalState7 = new MessageAction_SetDriverMentalState();
          driverMentalState7.SetEmotion(DriverMentalState.Emotion.VeryAngry);
          message17.messageAction = (MessageAction) driverMentalState7;
          message16.AddResponse(message17);
          Message message18 = MessageManager.CreateMessage();
          message18.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionOption3");
          message18.AddConversationResponseDelay();
          message18.SetSender((Person) player);
          message18.SetReceiver((Person) driver);
          message1.AddResponse(message18);
          Message message19 = MessageManager.CreateMessage();
          message19.description = Localisation.GetTextFromGroup("PessimisticAboutStartPositionOption3Response");
          message19.autoRespond = true;
          message19.AddConversationResponseDelay();
          message19.SetSender((Person) driver);
          message19.SetReceiver((Person) player);
          message18.AddResponse(message19);
          break;
        default:
          switch (emotion - 9)
          {
            case DriverMentalState.Emotion.Angry:
              message1.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipIntro");
              Message message20 = MessageManager.CreateMessage();
              message20.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipOption1");
              message20.AddConversationResponseDelay();
              message20.SetSender((Person) player);
              message20.SetReceiver((Person) driver);
              message1.AddResponse(message20);
              Message message21 = MessageManager.CreateMessage();
              message21.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipOption1Response");
              message21.autoRespond = true;
              message21.AddConversationResponseDelay();
              message21.SetSender((Person) driver);
              message21.SetReceiver((Person) player);
              MessageAction_SetDriverMentalState driverMentalState8 = new MessageAction_SetDriverMentalState();
              driverMentalState8.SetEmotion(DriverMentalState.Emotion.Focused);
              message21.messageAction = (MessageAction) driverMentalState8;
              message20.AddResponse(message21);
              Message message22 = MessageManager.CreateMessage();
              message22.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipOption2");
              message22.AddConversationResponseDelay();
              message22.SetSender((Person) player);
              message22.SetReceiver((Person) driver);
              message1.AddResponse(message22);
              Message message23 = MessageManager.CreateMessage();
              message23.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipOption2Response");
              message23.autoRespond = true;
              message23.AddConversationResponseDelay();
              message23.SetSender((Person) driver);
              message23.SetReceiver((Person) player);
              MessageAction_SetDriverMentalState driverMentalState9 = new MessageAction_SetDriverMentalState();
              driverMentalState9.SetEmotion(DriverMentalState.Emotion.Confident);
              message23.messageAction = (MessageAction) driverMentalState9;
              message22.AddResponse(message23);
              Message message24 = MessageManager.CreateMessage();
              message24.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipOption3");
              message24.AddConversationResponseDelay();
              message24.SetSender((Person) player);
              message24.SetReceiver((Person) driver);
              message1.AddResponse(message24);
              Message message25 = MessageManager.CreateMessage();
              message25.description = Localisation.GetTextFromGroup("ExcitedCouldWinChampionshipOption3Response");
              message25.autoRespond = true;
              message25.AddConversationResponseDelay();
              message25.SetSender((Person) driver);
              message25.SetReceiver((Person) player);
              MessageAction_SetDriverMentalState driverMentalState10 = new MessageAction_SetDriverMentalState();
              driverMentalState10.SetEmotion(DriverMentalState.Emotion.Focused);
              message25.messageAction = (MessageAction) driverMentalState10;
              message24.AddResponse(message25);
              break;
            case DriverMentalState.Emotion.VeryNervous:
              message1.description = Localisation.GetTextFromGroup("DisappointedBySeasonIntro");
              Message message26 = MessageManager.CreateMessage();
              message26.description = Localisation.GetTextFromGroup("DisappointedBySeasonOption1");
              message26.AddConversationResponseDelay();
              message26.SetSender((Person) player);
              message26.SetReceiver((Person) driver);
              message1.AddResponse(message26);
              Message message27 = MessageManager.CreateMessage();
              message27.description = Localisation.GetTextFromGroup("DisappointedBySeasonOption1Response");
              message27.autoRespond = true;
              message27.AddConversationResponseDelay();
              message27.SetSender((Person) driver);
              message27.SetReceiver((Person) player);
              MessageAction_SetDriverMentalState driverMentalState11 = new MessageAction_SetDriverMentalState();
              driverMentalState11.SetEmotion(DriverMentalState.Emotion.Angry);
              message27.messageAction = (MessageAction) driverMentalState11;
              message26.AddResponse(message27);
              Message message28 = MessageManager.CreateMessage();
              message28.description = Localisation.GetTextFromGroup("DisappointedBySeasonOption2");
              message28.AddConversationResponseDelay();
              message28.SetSender((Person) player);
              message28.SetReceiver((Person) driver);
              message1.AddResponse(message28);
              Message message29 = MessageManager.CreateMessage();
              message29.description = Localisation.GetTextFromGroup("DisappointedBySeasonOption2Response");
              message29.autoRespond = true;
              message29.AddConversationResponseDelay();
              message29.SetSender((Person) driver);
              message29.SetReceiver((Person) player);
              MessageAction_SetDriverMentalState driverMentalState12 = new MessageAction_SetDriverMentalState();
              driverMentalState12.SetEmotion(DriverMentalState.Emotion.VeryAngry);
              message29.messageAction = (MessageAction) driverMentalState12;
              message28.AddResponse(message29);
              Message message30 = MessageManager.CreateMessage();
              message30.description = Localisation.GetTextFromGroup("DisappointedBySeasonOption3");
              message30.AddConversationResponseDelay();
              message30.SetSender((Person) player);
              message30.SetReceiver((Person) driver);
              message1.AddResponse(message30);
              Message message31 = MessageManager.CreateMessage();
              message31.description = Localisation.GetTextFromGroup("DisappointedBySeasonOption3Response");
              message31.autoRespond = true;
              message31.AddConversationResponseDelay();
              message31.SetSender((Person) driver);
              message31.SetReceiver((Person) player);
              MessageAction_SetDriverMentalState driverMentalState13 = new MessageAction_SetDriverMentalState();
              driverMentalState13.SetEmotion(DriverMentalState.Emotion.Confident);
              message31.messageAction = (MessageAction) driverMentalState13;
              message30.AddResponse(message31);
              break;
          }
      }
      Game.instance.messageManager.PostMessage(message1);
    }
  }
}
